CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT,
    status TEXT,
    action TEXT,
    acknowledged INTEGER,
    note TEXT
);

-- Create initial admin user
INSERT OR IGNORE INTO users (username, password_hash, is_admin) 
VALUES ('admin', 'pbkdf2:sha256:260000$rMQDXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 1);

-- Note: Replace the password hash above with a secure hash generated by your application
